http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.cyrilb.me`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - dashboard-auth
      tls:
        certResolver: letsencrypt

    rudebooks:
      rule: "Host(`rudebooks.cyrilb.me`)"
      entryPoints:
        - websecure
      service: rudebooks-svc
      middlewares:
        - security-headers
      tls:
        certResolver: letsencrypt

  services:
    rudebooks-svc:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3002"

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - "dario:$apr1$FneDEecG$Vp8nUmQ7uLNdCNuyMECv/1"

    security-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: strict-origin-when-cross-origin
        customResponseHeaders:
          X-Powered-By: ""
          X-Hello: "We need a bigger boat"
